database:
  host: localhost
  port: 5432
  user: nba_user
  password: secure_password
  name: nba_db

api:
  base_url: https://api.nba.com/data

logging:
  config_path: src/config/logging.yaml

model:
  bayesian:
    num_samples: 1000
    chains: 4
  monte_carlo:
    num_simulations: 10000
